include: package:flutter_lints/flutter.yaml
linter:
  rules:
    unnecessary_overrides: false
    constant_identifier_names: false
    non_constant_identifier_names: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    library_private_types_in_public_api: false
    unnecessary_this: false
    
analyzer: 
  errors:
    todo: ignore
    
