name: ugodubai
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  url_strategy: ^0.2.0
  universal_html: 2.2.1
  flutx: ^0.2.0-rc.2
  url_launcher: 6.1.11
  google_fonts: ^4.0.4
  get_storage: 2.1.1
  animate_do: ^3.0.2
  flutter_svg: 2.0.6
  font_awesome_flutter: 10.4.0
  flex_color_scheme: 7.1.2
  hive: 2.2.3
  flutter_staggered_grid_view: 0.6.2
  flutter_blurhash: 0.7.0
  dartz: 0.10.1
  intl: 0.18.0
  sticky_headers: 0.3.0+2
  # syncfusion_flutter_datagrid: 22.1.37
  syncfusion_flutter_core: 22.1.37
  vertical_scrollable_tabview: 0.1.0
  scroll_to_index: 3.0.1
  syncfusion_localizations: 22.1.37
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/images/logo/
    - assets/images/dummy/
    - assets/datas/
    - assets/lang/
    - assets/locales/
  
  fonts:
      - family: UnsortIcon
        fonts:
          - asset: assets/font/UnsortIcon.ttf
      - family: FilterIcon
        fonts:
          - asset: assets/font/FilterIcon.ttf

  uses-material-design: true

